import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { Header } from '@/components/Header'
import { type NextPage } from 'next'
import { api } from '@/utils/api'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sem Dinheiro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  )
}

export default Home

const Content: React.FC = () => {
  const { data: sessionData } = useSession()

  const { data: transactions, refetch } =
    api.transaction.getMonthlyTransactions.useQuery(
      {
        month: new Date().getMonth() + 1,
        year: new Date().getFullYear(),
      },
      {
        enabled: !!sessionData?.user,
      },
    )

  return <div className="bg-neutral">Content</div>
}
